### PR TITLE
Feature enhancements: custom checksum, custom download url, custom basedir

### PR DESCRIPTION
**Pull request by angrox**
The following enhancements where made: 
- custom_checksum: Provide a custom checksum instead of the ones in the manifests
- custom_download_url: Download the packages from a custom url (i.e. your internal company repository server)
- custom_archive_dir: Specify own directory where the java tar.gz will be unzipped

### CODE REVIEW

**Comment by antoineco** [comment]
Looks good! Thank you very much for this @angrox \o/
Would you mind squashing these 4 commits before I merge the PR?

**Comment by antoineco** [comment]
:+1:

**Comment by antoineco** [comment]
Note to myself, before releasing:
- add warning if `custom_*` params used with rpm archive type
- don't create `custom_archive_path` in main installation if type == rpm
- add absolute path validation for `custom_archive_path`

**Comment by angrox** [comment]
Correct, I forgot the validations.

**Comment by antoineco** [comment]
No worries I will add them quickly tonight. I also renamed the 'custom_archive_path' param to 'install_path' because it's not an optional parameter. As soon as the validations are in I'll ship it in a v2.5.0.

**Comment by antoineco** [comment]
v2.5.0 [published](https://forge.puppetlabs.com/aco/oracle_java/changelog) on the Forge with these changes. Thanks again for your contribution :)

**Comment by antoineco** [comment]
@angrox you might want to check the CHANGELOG of v2.8.0 since the parameters you implemented here were renamed.

**Comment by angrox** [comment]
@antoineco Thanks, will have a look at it

**Pull request merged**
